<?php

namespace Tests\Feature\Category;

use App\Enums\RoleEnum;
use App\Models\Role;
use App\Models\User;
use Database\Seeders\RoleSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class StoreCategory extends TestCase
{
    use RefreshDatabase;

    private string $url;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->url = route('remark.store');
        $this->seed(RoleSeeder::class);
        $this->admin = Admin::factory()->create();
    }
}
