<?php

namespace Tests\Feature\Remark;

use App\Enums\RoleEnum;
use App\Models\Role;
use App\Models\User;
use Database\Seeders\RoleSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class StoreRemarkTest extends TestCase
{
    use RefreshDatabase;

    private string $url;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->url = route('remark.store');
        $this->seed(RoleSeeder::class);
        $this->admin = User::factory()->create();
        $this->user = User::factory()->create();
        $this->admin->roles()->attach(Role::get(RoleEnum::ADMIN));
        $this->user->roles()->attach(Role::get(RoleEnum::USER));
    }

    // test that only admin can add remarks
    public function test_only_admin_can_create_remark() {
        $data = [
            'name' => fake()->name,
            'description' => fake()->sentence,
            'image' => fake()->imageUrl
        ];
        $response = $this->actingAs($this->admin)->postJson($this->url, $data);

        $response->assertStatus(201);
        $response->assertJsonFragment(['name']);
    }

    // test that remark name is not empty
    public function test_remark_name_is_not_empty() {

    }

    // test that remark is unique
    public function test_remark_name_is_unique() {

    }

    // test public user cannot add remark
    public function test_guests_cannot_create_remark() {
        $response = $this->postJson($this->url);

        $response->assertUnauthorized();
    }
}
