<?php

namespace Tests\Feature\Roles;

use App\Models\Role;
use App\Models\User;
use Database\Seeders\RoleSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ListRolesTest extends TestCase
{
    use RefreshDatabase;
    private User $admin;
    private User $user;

    /**
     * setup global variables or methods
     * @return void
     */
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->seed(RoleSeeder::class);
        $this->admin = User::factory()->create();
        $this->user = User::factory()->create();
        $this->admin->roles()->attach(Role::where('name', 'admin')->first());
        $this->user->roles()->attach(Role::where('name','!=', 'admin')->first());
    }

    /**
     * A basic feature test example.
     */
    public function test_to_get_all_roles(): void
    {

        $response = $this->actingAs($this->admin)->get('/api/v1/admin/roles');

        // 200 status
        $response->assertStatus(200);
        $response->assertJsonCount(3, 'data');
        // check that it returns an array of roles
        $response->assertJsonFragment(['name' => 'admin']);
    }

    public function test_only_admin_can_get_roles(): void
    {

        $response = $this->actingAs($this->user)->get('/api/v1/admin/roles');

        // 200 status
        $response->assertStatus(403);
    }

    public function test_public_users_cannot_get_roles(): void
    {
        $response = $this->getJson('/api/v1/admin/roles');

        $response->assertStatus(401);
    }
}
