<?php

namespace Tests\Feature\Resume;

use App\Enums\RoleEnum;
use App\Models\Role;
use App\Models\User;
use Database\Seeders\RoleSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class CreateResumeTest extends TestCase
{
    use RefreshDatabase;

    private User $user;
    private string $url = '/api/v1/admin/users';
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->seed(RoleSeeder::class);
        $this->user = User::factory()->create();
        $this->user->roles()->attach(Role::get(RoleEnum::USER));
    }

    public function test_users_can_create_resume(): void {

        // assert that resume must be an array of resume, and must not be empty
        // assert that file is uploaded
    }

    public function test_public_users_cannot_create_resume(): void
    {
        $response = $this->getJson($this->url);

        $response->assertStatus(401);
    }
}
